#!/usr/bin/env bash
# Nginx

# Update and Install
sudo apt -y update
sudo apt -y install nginx

# rm mkdir

rm -rf school
mkdir school
mkdir school/errors
touch 404.html
echo "Ceci n'est pas une page" > school/errors/404.html

touch school/index.html
echo "Hello World!" > school/index.html

sudo rm -rf /var/www/school
sudo mv school /var/www/

# 404 error (page not found)

touch default
printf %s "server {
        listen 80;
        listen [::]:80;

        root /var/www/school;
        index index.html;

        location /redirect_me {
            return 301 https://youtube.com;
        }

        error_page 404 /404.html;
        location = /404.html {
            root /var/www/school/errors/;
        }
}
" > default

# rm
sudo rm -rf /etc/nginx/sites-available/default
sudo rm -rf /etc/nginx/sites-enabled/default
sudo mv default /etc/nginx/sites-available/
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart
sudo service nginx restart
